---
apiVersion: v1
kind: Service
metadata:
  name: varnish
  labels:
    app: django
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30085
    protocol: TCP
  selector:
    app: django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      tier: varnish
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: django
        tier: varnish
    spec:
      volumes:
      - name: varnish-config
        configMap:
          name: varnish-vcl
          items:
            - key: default.vcl
              path: default.vcl
      containers:
      - name: varnish
        image: million12/varnish
        env:
        - name: VCL_CONFIG
          value: /etc/varnish/default.vcl
        volumeMounts:
          - name: varnish-config
            mountPath: /etc/varnish/
        ports:
        - containerPort: 80